"""Module 5 -- free hypothesis search (TZ 9.5), logical-analysis approach.

TZ 9.5 ("Модуль свободного поиска нарушений") asks for findings that fall
*outside* the 132-parameter matrix, generated by up to four independent
discovery methods (logical analysis / semantic dissonance / normative
analysis / ML pattern analysis). Before this module, the only code that
produced a `SUSPICION` finding was `_create_gold_fixture_groups` in
`v3_pipeline.py`, which has no caller anywhere in `app` and, even if wired
in, only replays organizer-provided fixtures rather than computing a
hypothesis -- i.e. the module was entirely dead.

This file implements exactly one of the four approaches -- LOGICAL_ANALYSIS
("if A then B") -- for real, against actually extracted data, and is honest
about the other three still being unimplemented:

- SEMANTIC_DISSONANCE: not implemented here (see `semantic_dissonance.py`
  for a second, independent approach, wired in separately).
- NORMATIVE_ANALYSIS (a general SP/GOST/SanPiN checker outside the matrix):
  not implemented. The `LogicalRule` table below cites real normative
  paragraphs, but there is no general-purpose normative-document engine --
  every rule is hand-authored, not derived from a machine-readable norms
  base.
- ML_PATTERN_ANALYSIS: not implemented (no historical-anomaly model
  exists in this codebase yet).

A rule fires only when a real numeric value was actually extracted for its
condition parameter this run (an unparseable/missing condition is an honest
abstention, not a suspicion) *and* the implied check comes back negative.
"Negative" here means "no corroborating evidence was found", which is a
signal for the inspector to look, not proof that the implied fact is false
-- consistent with TZ 9.5's own framing of a Suspicion as a hypothesis, not
a violation (see `finding_status = SUSPICION`, excluded from
`training_release.FORBIDDEN_TRAINING_LABELS` and from every violation count
in `protocol_annex2.py`).
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from sqlalchemy.orm import Session

from ..db.models import DocumentVersion, EvidenceFragment, EvidenceGroup, InspectionProcess, LogicalRuleRecord, Param, SourceFragment, Suspicion
from .evidence_groups import upsert_evidence_group
from .normalization import normalize_text


DISCOVERY_METHOD_LOGICAL_ANALYSIS = "LOGICAL_ANALYSIS"
MODEL_VERSION_LOGICAL_ANALYSIS = "logical-analysis-v1"

_NUMBER_RE = re.compile(r"-?\d+(?:[.,]\d+)?")


@dataclass(frozen=True)
class LogicalRule:
    """One row of the TZ-10 `Logical_Rules` table (`id, rule_name, condition,
    expected, normative_base, is_active`), expanded into the fields this
    engine needs to evaluate it. `condition` = (condition_param_code,
    condition_op, condition_value); `expected` = the implied check."""

    rule_id: str
    rule_name: str
    is_active: bool
    condition_param_code: str
    condition_op: str  # ">" | ">=" | "<" | "<=" | "=="
    condition_value: float
    condition_description: str
    implied_check: str  # "PARAM_EVIDENCE_PRESENT" | "TEXT_KEYWORD_PRESENT"
    implied_description: str
    normative_base: str
    criticality: str  # "КРИТИЧЕСКОЕ" | "СУЩЕСТВЕННОЕ"
    confidence: float
    implied_param_code: str | None = None
    implied_discipline: str | None = None
    implied_keywords: tuple[str, ...] = field(default_factory=tuple)


LOGICAL_RULES: tuple[LogicalRule, ...] = (
    LogicalRule(
        rule_id="LR-001",
        rule_name="Этажность -> лифт",
        is_active=True,
        condition_param_code="PZ-007",
        condition_op=">=",
        condition_value=6,
        condition_description="Этажность здания (надземная) достигает 6 этажей и более",
        implied_check="PARAM_EVIDENCE_PRESENT",
        implied_param_code="KR-064",
        implied_description="в РД/ИД должны быть данные о привязках и габаритах лифтовой шахты (КР-064)",
        normative_base="СП 54.13330.2022 «Здания жилые многоквартирные» (пассажирские лифты предусматриваются, "
                        "когда отметка пола верхнего жилого этажа превышает уровень земли более чем на 12 м -- "
                        "практически с 6-го этажа при типовой высоте этажа)",
        criticality="СУЩЕСТВЕННОЕ",
        confidence=0.55,
    ),
    LogicalRule(
        rule_id="LR-002",
        rule_name="Этажность -> незадымляемая лестничная клетка",
        is_active=True,
        condition_param_code="PZ-007",
        condition_op=">=",
        condition_value=6,
        condition_description="Этажность здания (надземная) достигает 6 этажей и более",
        implied_check="TEXT_KEYWORD_PRESENT",
        implied_discipline="AR",
        implied_keywords=(
            "незадымляем",
            "лестничная клетка типа н1",
            "лестничная клетка типа н2",
            "лестничная клетка типа н3",
            "лестница типа н1",
            "лестница типа н2",
        ),
        implied_description="в архитектурном разделе РД/ИД должна упоминаться незадымляемая лестничная клетка "
                             "(тип Н1/Н2/Н3)",
        normative_base="СП 1.13130.2020 «Системы противопожарной защиты. Эвакуационные пути и выходы», разд. 4 "
                        "(лестничные клетки зданий повышенной этажности проектируются незадымляемыми)",
        criticality="СУЩЕСТВЕННОЕ",
        confidence=0.45,
    ),
    LogicalRule(
        rule_id="LR-003",
        rule_name="Подземная парковка -> вентиляция автостоянки",
        is_active=True,
        condition_param_code="PZ-012",
        condition_op=">",
        condition_value=0,
        condition_description="На объекте есть подземные машино-места (PZ-012 > 0)",
        implied_check="PARAM_EVIDENCE_PRESENT",
        implied_param_code="IOS4-079",
        implied_description="должны быть данные о характеристиках вентиляторов общеобменной вентиляции "
                             "автостоянки (IOS4-079)",
        normative_base="СП 113.13330.2016 «Стоянки автомобилей», разд. 6 (закрытые и подземные автостоянки "
                        "оборудуются приточно-вытяжной механической вентиляцией; для рабочего режима -- не менее "
                        "150 м³/ч вытяжки на одно машино-место)",
        criticality="КРИТИЧЕСКОЕ",
        confidence=0.5,
    ),
)


def _first_number(text: object) -> float | None:
    if not text:
        return None
    match = _NUMBER_RE.search(str(text).replace("\xa0", " "))
    if not match:
        return None
    try:
        return float(match.group(0).replace(",", "."))
    except ValueError:
        return None


def _condition_met(op: str, observed: float, threshold: float) -> bool:
    if op == ">":
        return observed > threshold
    if op == ">=":
        return observed >= threshold
    if op == "<":
        return observed < threshold
    if op == "<=":
        return observed <= threshold
    if op == "==":
        return observed == threshold
    raise ValueError(f"Unsupported logical-rule operator: {op!r}")


def _condition_observation(db: Session, process: InspectionProcess, condition_param: Param) -> tuple[float, EvidenceGroup] | None:
    """The most confident already-extracted numeric value for `condition_param`
    in this process, read back from whatever mechanism produced it (rule
    pack / generic anchor / enum / compound / table-count / annotation).
    Never reads a `suspicion:*` group -- a Module-5 finding can never feed
    another Module-5 rule's condition."""
    rows = (
        db.query(EvidenceGroup)
        .filter(EvidenceGroup.process_id == process.id, EvidenceGroup.param_id == int(condition_param.id))
        .all()
    )
    best: tuple[float, EvidenceGroup, float] | None = None
    for row in rows:
        if not row.group_key or row.group_key.startswith("suspicion:"):
            continue
        for raw in (row.actual_value, row.expected_value):
            value = _first_number(raw)
            if value is None:
                continue
            confidence = row.confidence or 0.0
            if best is None or confidence > best[2]:
                best = (value, row, confidence)
            break
    if best is None:
        return None
    return best[0], best[1]


def _implied_param_evidence_present(db: Session, process: InspectionProcess, implied_param: Param) -> bool:
    return (
        db.query(EvidenceGroup.id)
        .filter(
            EvidenceGroup.process_id == process.id,
            EvidenceGroup.param_id == int(implied_param.id),
            EvidenceGroup.comparability_status == "COMPARABLE",
        )
        .first()
        is not None
    )


def _keyword_evidence_fragment(
    fragments: list[SourceFragment],
    by_id: dict[int, DocumentVersion],
    *,
    discipline: str | None,
    keywords: tuple[str, ...],
) -> SourceFragment | None:
    """A substring search over already-extracted document text (OCR/PDF text
    layer), never over `learning_annotation` fragments -- this module reads
    real document content the same way any other extractor does, it does
    not touch organizer-provided gold hints. A straightforward per-fragment
    substring match: it can miss a phrase split across two fragments by the
    upstream text extractor, which is a known, acceptable limitation for a
    hypothesis-generation heuristic (a miss here costs a missed suspicion,
    never a false violation)."""
    needles = [normalize_text(keyword) for keyword in keywords]
    for fragment in fragments:
        if fragment.source_system == "learning_annotation":
            continue
        doc = by_id.get(fragment.document_version_id)
        if doc is None:
            continue
        if discipline and (doc.discipline or "").upper() != discipline.upper():
            continue
        text = normalize_text(fragment.text)
        if not text:
            continue
        if any(needle in text for needle in needles):
            return fragment
    return None


def _priority_from_criticality(value: str) -> str:
    return "HIGH" if value == "КРИТИЧЕСКОЕ" else "MEDIUM"


def _fragment_reference(fragment: EvidenceFragment | None) -> str | None:
    if fragment is None:
        return None
    bits = [str(fragment.document_code)] if fragment.document_code else []
    if fragment.page is not None:
        bits.append(f"л.{fragment.page}")
    return ", ".join(bits) or None


def _find_param(db: Session, params_by_code: dict[str, Param], matrix_version_id: int, code: str) -> Param | None:
    param = params_by_code.get(code)
    if param is not None:
        return param
    return (
        db.query(Param)
        .filter(Param.matrix_version_id == int(matrix_version_id), Param.code == code, Param.is_active == True)  # noqa: E712
        .first()
    )


def _db_rule_activity(db: Session) -> dict[str, bool]:
    """`is_active` overrides an admin has set on the `logical_rules` table
    (ТЗ-10), keyed by `rule_id`. A rule with no matching row (DB not seeded
    yet, e.g. a test that only calls `Base.metadata.create_all`) falls back
    to the code-level `LogicalRule.is_active` default -- this table is an
    override, not a hard requirement."""
    return {
        row.rule_id: bool(row.is_active)
        for row in db.query(LogicalRuleRecord.rule_id, LogicalRuleRecord.is_active).all()
    }


def run_logical_analysis_module(
    db: Session,
    process: InspectionProcess,
    params: list[Param],
    touched_keys: dict[int, set[str]],
    *,
    fragments: list[SourceFragment],
    by_id: dict[int, DocumentVersion],
    user_id: int | None = None,
) -> list[str]:
    """Evaluate every active `LogicalRule` whose condition parameter is in
    this run's scope (`params`), and upsert a SUSPICION `EvidenceGroup` for
    each one that fires. Must run *before* the caller's own
    `sweep_orphaned_evidence_groups` call and share its `touched_keys` dict:
    a rule's condition parameter is a real matrix `Param`, so any group this
    module writes under that `param_id` would otherwise look "orphaned" (not
    produced by this run) to that sweep and get deleted on the spot. A rule
    that no longer fires (condition became false, or the implied evidence
    now exists) is deliberately left untouched here so that same sweep call
    reconciles/removes its stale suspicion exactly like any other mechanism.

    Returns the rule_ids that produced a suspicion this run (for tests/audit
    logging), not the touched_keys themselves.
    """
    params_by_code = {p.code: p for p in params}
    db_activity = _db_rule_activity(db)
    fired: list[str] = []
    for rule in LOGICAL_RULES:
        if not db_activity.get(rule.rule_id, rule.is_active):
            continue
        condition_param = params_by_code.get(rule.condition_param_code)
        if condition_param is None:
            # Out of this (possibly incrementally-scoped) run's param scope --
            # leave any existing suspicion for this rule exactly as it is.
            continue
        observation = _condition_observation(db, process, condition_param)
        if observation is None:
            continue
        observed_value, condition_group = observation
        if not _condition_met(rule.condition_op, observed_value, rule.condition_value):
            continue

        implied_satisfied: bool
        if rule.implied_check == "PARAM_EVIDENCE_PRESENT":
            implied_param = _find_param(db, params_by_code, condition_param.matrix_version_id, rule.implied_param_code or "")
            if implied_param is None:
                continue
            implied_satisfied = _implied_param_evidence_present(db, process, implied_param)
        elif rule.implied_check == "TEXT_KEYWORD_PRESENT":
            hit = _keyword_evidence_fragment(fragments, by_id, discipline=rule.implied_discipline, keywords=rule.implied_keywords)
            implied_satisfied = hit is not None
        else:
            raise ValueError(f"Unsupported implied_check: {rule.implied_check!r}")

        if implied_satisfied:
            continue

        param_touched = touched_keys.setdefault(int(condition_param.id), set())
        group_key = f"suspicion:logical:{rule.rule_id}"
        param_touched.add(group_key)
        _upsert_logical_suspicion(db, process, condition_param, rule, observed_value, condition_group, user_id=user_id)
        fired.append(rule.rule_id)
    return fired


def _upsert_logical_suspicion(
    db: Session,
    process: InspectionProcess,
    condition_param: Param,
    rule: LogicalRule,
    observed_value: float,
    condition_group: EvidenceGroup,
    *,
    user_id: int | None = None,
) -> None:
    condition_fragments = (
        db.query(EvidenceFragment)
        .filter(EvidenceFragment.evidence_group_id == int(condition_group.id))
        .order_by(EvidenceFragment.role.asc(), EvidenceFragment.id.asc())
        .all()
    )
    pd_fragment = next((f for f in condition_fragments if f.role == "expected"), None)
    rd_fragment = next((f for f in condition_fragments if f.role in ("actual", "context")), None)
    observed_display = f"{observed_value:g}"
    description = (
        f"{rule.condition_description} (наблюдаемое значение: {observed_display}), но {rule.implied_description} "
        f"-- подтверждающих данных не найдено."
    )
    group_key = f"suspicion:logical:{rule.rule_id}"
    fragment_specs: list[dict[str, Any]] = [
        {
            "document_version_id": f.document_version_id,
            "source_fragment_id": f.source_fragment_id,
            "file_sha256": f.file_sha256,
            "dataset_file_id": f.dataset_file_id,
            "stage": f.stage,
            "discipline": f.discipline,
            "document_code": f.document_code,
            "revision": f.revision,
            "approval_status": f.approval_status,
            "page": f.page,
            "bbox": f.bbox,
            "bbox_pdf": f.bbox_pdf,
            "page_width": f.page_width,
            "page_height": f.page_height,
            "polygon": f.polygon,
            "extracted_value": f.extracted_value,
            "role": "context",
            "context": f.context,
            "extractor": "logical_analysis_module5",
            "confidence": rule.confidence,
        }
        for f in condition_fragments
    ]
    group, should_write_fragments = upsert_evidence_group(
        db, process, condition_param, group_key,
        fields={
            "matrix_version": process.matrix_version,
            "model_version": MODEL_VERSION_LOGICAL_ANALYSIS,
            "dataset_version": process.dataset_version,
            "comparison_scenario": process.upload_scenario,
            "completeness_status": "COMPLETE",
            "comparability_status": "COMPARABLE",
            "finding_status": "SUSPICION",
            "expected_value": rule.implied_description,
            "actual_value": observed_display,
            "review_priority": _priority_from_criticality(rule.criticality),
            "confidence": rule.confidence,
            "delta": {
                "source": "logical_analysis_module5",
                "matrix_scope": "FREE_SEARCH",
                "discovery_method": DISCOVERY_METHOD_LOGICAL_ANALYSIS,
                "rule_id": rule.rule_id,
                "rule_name": rule.rule_name,
                "description": description,
                "pd_reference": _fragment_reference(pd_fragment),
                "rd_reference": _fragment_reference(rd_fragment),
                "criticality": rule.criticality,
                "normative_base": rule.normative_base,
                "inspector_status": "PENDING",
                "condition": {
                    "param_code": condition_param.code,
                    "operator": rule.condition_op,
                    "threshold": rule.condition_value,
                    "observed_value": observed_value,
                },
                "implied": {
                    "check": rule.implied_check,
                    "param_code": rule.implied_param_code,
                    "keywords": list(rule.implied_keywords) or None,
                },
            },
        },
        fragment_specs=fragment_specs,
        user_id=user_id,
    )
    if group is not None and should_write_fragments:
        for spec in fragment_specs:
            db.add(EvidenceFragment(evidence_group_id=group.id, **spec))
        db.flush()
    if group is not None:
        _upsert_suspicion_row(
            db, process, group,
            discovery_method=DISCOVERY_METHOD_LOGICAL_ANALYSIS,
            confidence=rule.confidence,
            description=description,
            pd_reference=_fragment_reference(pd_fragment),
            rd_reference=_fragment_reference(rd_fragment),
            criticality=rule.criticality,
            normative_base=rule.normative_base,
        )


def _upsert_suspicion_row(
    db: Session,
    process: InspectionProcess,
    group: EvidenceGroup,
    *,
    discovery_method: str,
    confidence: float | None,
    description: str | None,
    pd_reference: str | None,
    rd_reference: str | None,
    criticality: str | None,
    normative_base: str | None,
) -> Suspicion:
    """Materialize the ТЗ-10 `Suspicions` row for a SUSPICION `EvidenceGroup`
    (one-to-one, keyed by `evidence_group_id`). Cascade-deleted along with the
    group when `sweep_orphaned_evidence_groups` removes a suspicion that no
    longer fires."""
    row = db.query(Suspicion).filter(Suspicion.evidence_group_id == int(group.id)).first()
    if row is None:
        row = Suspicion(evidence_group_id=int(group.id))
    row.process_id = str(process.id)
    row.project_id = int(process.project_id)
    row.organization_id = int(process.organization_id)
    row.object_id = group.object_id
    row.discovery_method = discovery_method
    row.confidence = confidence
    row.description = description
    row.pd_reference = pd_reference
    row.rd_reference = rd_reference
    row.criticality = criticality
    row.normative_base = normative_base
    db.add(row)
    db.flush()
    return row
