"""add tz10 rejection dispute suspicion logical_rules normative_base monitoring_metrics tables

Revision ID: 8ec8d78d4240
Revises: 
Create Date: 2026-09-21 13:10:02.101811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec8d78d4240'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logical_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('normative_base', sa.Text(), nullable=True),
    sa.Column('criticality', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logical_rules_id'), 'logical_rules', ['id'], unique=False)
    op.create_index(op.f('ix_logical_rules_is_active'), 'logical_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_logical_rules_rule_id'), 'logical_rules', ['rule_id'], unique=True)
    op.create_table('monitoring_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_metrics_id'), 'monitoring_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_metric_name'), 'monitoring_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_service_name'), 'monitoring_metrics', ['service_name'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_timestamp'), 'monitoring_metrics', ['timestamp'], unique=False)
    op.create_table('normative_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=512), nullable=False),
    sa.Column('document_number', sa.String(length=128), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('parameter_name', sa.String(length=255), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normative_base_created_by_user_id'), 'normative_base', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_normative_base_document_number'), 'normative_base', ['document_number'], unique=False)
    op.create_index(op.f('ix_normative_base_id'), 'normative_base', ['id'], unique=False)
    op.create_index(op.f('ix_normative_base_is_active'), 'normative_base', ['is_active'], unique=False)
    op.create_index(op.f('ix_normative_base_parameter_name'), 'normative_base', ['parameter_name'], unique=False)
    op.create_index(op.f('ix_normative_base_section'), 'normative_base', ['section'], unique=False)
    op.create_table('dispute_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_group_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('inspector_comment', sa.Text(), nullable=False),
    sa.Column('ai_comment', sa.Text(), nullable=True),
    sa.Column('resolution_status', sa.String(length=32), server_default='OPEN', nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_group_id'], ['evidence_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_logs_evidence_group_id'), 'dispute_logs', ['evidence_group_id'], unique=False)
    op.create_index(op.f('ix_dispute_logs_id'), 'dispute_logs', ['id'], unique=False)
    op.create_index(op.f('ix_dispute_logs_opened_by_user_id'), 'dispute_logs', ['opened_by_user_id'], unique=False)
    op.create_index(op.f('ix_dispute_logs_organization_id'), 'dispute_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dispute_logs_process_id'), 'dispute_logs', ['process_id'], unique=False)
    op.create_index(op.f('ix_dispute_logs_project_id'), 'dispute_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_dispute_logs_resolution_status'), 'dispute_logs', ['resolution_status'], unique=False)
    op.create_index(op.f('ix_dispute_logs_resolved_by_user_id'), 'dispute_logs', ['resolved_by_user_id'], unique=False)
    op.create_table('suspicions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_group_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('discovery_method', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pd_reference', sa.String(length=255), nullable=True),
    sa.Column('rd_reference', sa.String(length=255), nullable=True),
    sa.Column('criticality', sa.String(length=64), nullable=True),
    sa.Column('normative_base', sa.Text(), nullable=True),
    sa.Column('inspector_status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_group_id'], ['evidence_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspicions_discovery_method'), 'suspicions', ['discovery_method'], unique=False)
    op.create_index(op.f('ix_suspicions_evidence_group_id'), 'suspicions', ['evidence_group_id'], unique=True)
    op.create_index(op.f('ix_suspicions_id'), 'suspicions', ['id'], unique=False)
    op.create_index(op.f('ix_suspicions_inspector_status'), 'suspicions', ['inspector_status'], unique=False)
    op.create_index(op.f('ix_suspicions_object_id'), 'suspicions', ['object_id'], unique=False)
    op.create_index(op.f('ix_suspicions_organization_id'), 'suspicions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_suspicions_process_id'), 'suspicions', ['process_id'], unique=False)
    op.create_index(op.f('ix_suspicions_project_id'), 'suspicions', ['project_id'], unique=False)
    op.create_table('rejection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_group_id', sa.Integer(), nullable=False),
    sa.Column('evidence_decision_id', sa.Integer(), nullable=True),
    sa.Column('process_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('ai_verdict', sa.String(length=32), nullable=True),
    sa.Column('ai_verdict_comment', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('retraining_status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_decision_id'], ['evidence_decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_group_id'], ['evidence_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rejection_logs_ai_verdict'), 'rejection_logs', ['ai_verdict'], unique=False)
    op.create_index(op.f('ix_rejection_logs_evidence_decision_id'), 'rejection_logs', ['evidence_decision_id'], unique=False)
    op.create_index(op.f('ix_rejection_logs_evidence_group_id'), 'rejection_logs', ['evidence_group_id'], unique=False)
    op.create_index(op.f('ix_rejection_logs_id'), 'rejection_logs', ['id'], unique=False)
    op.create_index(op.f('ix_rejection_logs_organization_id'), 'rejection_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rejection_logs_process_id'), 'rejection_logs', ['process_id'], unique=False)
    op.create_index(op.f('ix_rejection_logs_project_id'), 'rejection_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_rejection_logs_retraining_status'), 'rejection_logs', ['retraining_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rejection_logs_retraining_status'), table_name='rejection_logs')
    op.drop_index(op.f('ix_rejection_logs_project_id'), table_name='rejection_logs')
    op.drop_index(op.f('ix_rejection_logs_process_id'), table_name='rejection_logs')
    op.drop_index(op.f('ix_rejection_logs_organization_id'), table_name='rejection_logs')
    op.drop_index(op.f('ix_rejection_logs_id'), table_name='rejection_logs')
    op.drop_index(op.f('ix_rejection_logs_evidence_group_id'), table_name='rejection_logs')
    op.drop_index(op.f('ix_rejection_logs_evidence_decision_id'), table_name='rejection_logs')
    op.drop_index(op.f('ix_rejection_logs_ai_verdict'), table_name='rejection_logs')
    op.drop_table('rejection_logs')
    op.drop_index(op.f('ix_suspicions_project_id'), table_name='suspicions')
    op.drop_index(op.f('ix_suspicions_process_id'), table_name='suspicions')
    op.drop_index(op.f('ix_suspicions_organization_id'), table_name='suspicions')
    op.drop_index(op.f('ix_suspicions_object_id'), table_name='suspicions')
    op.drop_index(op.f('ix_suspicions_inspector_status'), table_name='suspicions')
    op.drop_index(op.f('ix_suspicions_id'), table_name='suspicions')
    op.drop_index(op.f('ix_suspicions_evidence_group_id'), table_name='suspicions')
    op.drop_index(op.f('ix_suspicions_discovery_method'), table_name='suspicions')
    op.drop_table('suspicions')
    op.drop_index(op.f('ix_dispute_logs_resolved_by_user_id'), table_name='dispute_logs')
    op.drop_index(op.f('ix_dispute_logs_resolution_status'), table_name='dispute_logs')
    op.drop_index(op.f('ix_dispute_logs_project_id'), table_name='dispute_logs')
    op.drop_index(op.f('ix_dispute_logs_process_id'), table_name='dispute_logs')
    op.drop_index(op.f('ix_dispute_logs_organization_id'), table_name='dispute_logs')
    op.drop_index(op.f('ix_dispute_logs_opened_by_user_id'), table_name='dispute_logs')
    op.drop_index(op.f('ix_dispute_logs_id'), table_name='dispute_logs')
    op.drop_index(op.f('ix_dispute_logs_evidence_group_id'), table_name='dispute_logs')
    op.drop_table('dispute_logs')
    op.drop_index(op.f('ix_normative_base_section'), table_name='normative_base')
    op.drop_index(op.f('ix_normative_base_parameter_name'), table_name='normative_base')
    op.drop_index(op.f('ix_normative_base_is_active'), table_name='normative_base')
    op.drop_index(op.f('ix_normative_base_id'), table_name='normative_base')
    op.drop_index(op.f('ix_normative_base_document_number'), table_name='normative_base')
    op.drop_index(op.f('ix_normative_base_created_by_user_id'), table_name='normative_base')
    op.drop_table('normative_base')
    op.drop_index(op.f('ix_monitoring_metrics_timestamp'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_service_name'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_metric_name'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_id'), table_name='monitoring_metrics')
    op.drop_table('monitoring_metrics')
    op.drop_index(op.f('ix_logical_rules_rule_id'), table_name='logical_rules')
    op.drop_index(op.f('ix_logical_rules_is_active'), table_name='logical_rules')
    op.drop_index(op.f('ix_logical_rules_id'), table_name='logical_rules')
    op.drop_table('logical_rules')
    # ### end Alembic commands ###
